import type { DemoState } from "./model";
export function legacySnapshot(state: DemoState) {
    const tasks = state.tasks.map(t => ({ id: t.taskId, monthlyPlanId: t.monthlyPlanId, publishDate: (t.scheduledAt || t.updatedAt).slice(0, 10), officialLinkTarget: "/demo-article/product-guide", primaryDistilledTerm: "任务可追溯", title: t.title, product: t.productId === "orbitdesk" ? "joto_brand" : "weike_guardrails", channel: t.channel === "zhihu" ? "zhihu_toutiao_general" : t.channel, contentType: "scenario", status: t.status === "published" ? "published" : "approved", scheduledDate: t.scheduledAt?.slice(0, 10), plannedDate: t.scheduledAt?.slice(0, 10), draftId: t.formalDraftId, distilledTerms: ["任务可追溯"], knowledgeBaseIds: t.knowledgeBaseIds, rulePackageVersion: "1", evidenceIds: [`source-${t.productId}`], createdAt: state.now, updatedAt: state.now }));
    const drafts = state.tasks.map(t => ({ id: t.formalDraftId, taskId: t.taskId, title: t.title, body: t.currentDraft?.markdown || "", markdown: t.currentDraft?.markdown || "", content: t.currentDraft?.markdown || "", status: "approved", version: 1, summary: "虚拟内容示例", qualityScore: 92, qaResult: { passed: true, copyAllowed: true, score: 92, issues: [], blockers: [], warnings: [], failedSegments: [], editActions: [] }, evidenceIds: [`source-${t.productId}`], citations: [], qaIssues: [], createdAt: state.now, updatedAt: state.now }));
    const publishRecords = state.tasks.filter(t => t.status === "published").map(t => ({ id: `publish-${t.taskId}`, taskId: t.taskId, channel: t.channel === "zhihu" ? "zhihu_toutiao_general" : t.channel, platform: t.channel, title: t.title, url: t.publicUrl, publicUrl: t.publicUrl, status: "published", publishedAt: t.updatedAt, metrics: { views: 240, likes: 18, favorites: 8 }, dataConfidence: "demo", metricSource: "demo", createdAt: state.now, updatedAt: state.now }));
    const knowledgeBases = state.knowledge.map(k => ({ ...k, kind: "product", description: k.description, source: "demo", dataConfidence: "demo", useCount: 6, totalChars: 1200, vectorizedCount: 8, embeddingStatus: "ready", fileName: "virtual-product-guide.md", content: k.materials.map((m: any) => m.evidenceExcerpt).join("\n"), chunks: k.materials.map((m: any, i: number) => ({ id: `chunk-${i}`, text: m.evidenceExcerpt, content: m.evidenceExcerpt, tokenCount: 80 })), tags: ["虚拟资料"], version: 1, documentCount: k.materials.length }));
    const auditLog = state.events.map(e => ({ id: e.id, action: e.action, entityId: e.objectId, entityType: "demo", actor: "demo-user", role: "content_publisher", detail: e.summary, summary: e.summary, createdAt: e.at }));
    return { state: { runtime: { storage: "local_json", statePath: "browser:demo", initializedAt: state.now }, workspaceSetting: state.settings, tasks, drafts, publishRecords, platformDraftVariants: [], distributionTargets: [], publishSchedules: [], publishAttempts: [], blogArticles: [{ id: "demo-blog", title: "虚拟产品说明", url: "/demo-article/product-guide", publishedAt: state.now, status: "published", product: "joto_brand", dataConfidence: "demo", botVisits: 12 }], botVisits: [{ id: "demo-bot", bot: "DemoBot", botName: "DemoBot", date: state.now.slice(0, 10), visits: 12, count: 12, articleId: "demo-blog", dataConfidence: "demo" }], knowledgeBases, distilledTerms: state.questions.map(q => ({ id: q.questionId, term: q.questionText, level: "product", source: "虚拟调研", validationStatus: "auto_validated", modelConsensusCount: 3, status: "active", coveredContentTypes: ["scenario"], geoLift: 0, competitorOccupied: false })), distilledTermExtractionRules: [], distilledTermRuleDrafts: [], promptVersions: [], pipelineRuns: state.events.map(e => ({ id: e.id, status: "completed", startedAt: e.at, completedAt: e.at, stages: [], summary: e.summary })), auditLog }, summary: { planned: tasks.length, generated: drafts.length, published: publishRecords.length, totalTasks: tasks.length, publishedCount: publishRecords.length, pendingReviewCount: 0, failedCount: state.tasks.filter(t => t.failureReason).length, blogVisits: 12, geoScore: 75 } };
}
