export interface DemoPageCase {
    route: string;
    href: string;
    expected: string;
    group: string;
}
const product = "orbitdesk", order = "demo-order-orbitdesk";
const rows: Array<[
    string,
    string,
    string,
    string
]> = [
    ["/", "/", "OrbitDesk", "托管"],
    ["/hosted/login", "/hosted/login", "OrbitDesk", "托管"],
    ["/hosted/login/verify", "/hosted/login/verify#token=demo-login", "OrbitDesk", "托管"],
    ["/hosted/success", `/hosted/success?orderId=${order}`, "系统正在按本轮计划自动发布", "托管"],
    ["/hosted/email", `/hosted/email?orderId=${order}`, "公开结果与状态", "邮件"],
    ["/hosted/history", `/hosted/history?orderId=${order}&step=research`, "步骤历史结果", "托管"],
    ["/hosted/review/[token]", "/hosted/review/demo-strategy", "核心表达", "邮件"],
    ["/hosted/preferences/[token]", "/hosted/preferences/demo-preferences", "保存通知偏好", "邮件"],
    ["/hosted/settings", `/hosted/settings?orderId=${order}`, "结果通知", "托管"],
    ["/hosted/connections", `/hosted/connections?orderId=${order}`, "星屿实验室", "托管"],
    ["/hosted/connect/[channel]", `/hosted/connect/zhihu?orderId=${order}`, "已连接", "托管"],
    ["/hosted/browser-session/[sessionId]", "/hosted/browser-session/demo-session-zhihu", "账号识别完成", "托管"],
    ["/hosted/email-sender", "/hosted/email-sender", "邮箱", "邮件"],
    ["/products", "/products", "OrbitDesk", "知识"],
    ["/products/new", "/products/new", "产品", "知识"],
    ["/products/[productId]", `/products/${product}`, "虚拟产品", "知识"],
    ["/products/[productId]/research", `/products/${product}/research`, "GEO", "调研"],
    ["/products/[productId]/research/[runId]", `/products/${product}/research/run-${product}`, "任务交接", "调研"],
    ["/products/[productId]/samples", `/products/${product}/samples`, "样文", "正文"],
    ["/products/[productId]/samples/[taskId]", `/products/${product}/samples/demo-task-1`, "协作闭环", "正文"],
    ["/products/sources", "/products/sources", "虚拟资料源", "知识"],
    ["/knowledge", "/knowledge", "OrbitDesk", "知识"],
    ["/knowledge/[id]", "/knowledge/kb-orbitdesk", "虚拟产品说明", "知识"],
    ["/knowledge/import", "/knowledge/import", "OrbitDesk", "知识"],
    ["/knowledge/import/url", "/knowledge/import/url", "OrbitDesk", "知识"],
    ["/knowledge/import/document", "/knowledge/import/document", "OrbitDesk", "知识"],
    ["/knowledge/rule-packages", "/knowledge/rule-packages", "OrbitDesk", "知识"],
    ["/knowledge/vectorize", "/knowledge/vectorize", "OrbitDesk", "知识"],
    ["/questions-keywords", "/questions-keywords", "已复测", "调研"],
    ["/distilled-terms", "/distilled-terms", "已复测", "调研"],
    ["/content-automation", "/content-automation", "从任务输入到可追溯的交付结果", "生产"],
    ["/monthly-plan", "/monthly-plan", "从任务输入到可追溯的交付结果", "生产"],
    ["/monthly-strategy", "/monthly-strategy", "从任务输入到可追溯的交付结果", "生产"],
    ["/monthly-matrix", "/monthly-matrix", "从任务输入到可追溯的交付结果", "生产"],
    ["/monthly-matrix/strategy", "/monthly-matrix/strategy", "从任务输入到可追溯的交付结果", "生产"],
    ["/monthly-matrix/tasks", "/monthly-matrix/tasks", "从任务输入到可追溯的交付结果", "生产"],
    ["/monthly-matrix/batch-generation", "/monthly-matrix/batch-generation", "从任务输入到可追溯的交付结果", "生产"],
    ["/monthly-matrix/schedule", "/monthly-matrix/schedule", "从任务输入到可追溯的交付结果", "生产"],
    ["/monthly-matrix/content-types", "/monthly-matrix/content-types", "场景解读", "生产"],
    ["/batch-generation", "/batch-generation", "从任务输入到可追溯的交付结果", "生产"],
    ["/daily-execution", "/daily-execution", "从任务输入到可追溯的交付结果", "生产"],
    ["/today", "/today", "从任务输入到可追溯的交付结果", "生产"],
    ["/exceptions", "/exceptions", "从任务输入到可追溯的交付结果", "生产"],
    ["/drafts/[taskId]", "/drafts/demo-task-1", "质检通过", "正文"],
    ["/v5/drafts/[id]", "/v5/drafts/demo-draft-1", "从任务输入到可追溯的交付结果", "正文"],
    ["/free-production", "/free-production", "场景解读", "正文"],
    ["/free-production/tasks", "/free-production/tasks", "协作", "正文"],
    ["/free-production/content-types", "/free-production/content-types", "场景解读", "正文"],
    ["/free-production/assets", "/free-production/assets", "OrbitDesk", "正文"],
    ["/content-monitor", "/content-monitor", "近30天内容表现", "监控"],
    ["/geo-monitor", "/geo-monitor", "近30天内容表现", "监控"],
    ["/publish", "/publish", "内容表现明细", "监控"],
    ["/publishing", "/publishing", "内容表现明细", "监控"],
    ["/publish-schedule", "/publish-schedule", "内容表现明细", "监控"],
    ["/publish-schedule/daily-execution", "/publish-schedule/daily-execution", "从任务输入到可追溯的交付结果", "生产"],
    ["/blog-monitor", "/blog-monitor", "官网监控", "监控"],
    ["/blog-candidates", "/blog-candidates", "官网监控", "监控"],
    ["/monthly-review", "/monthly-review", "产品下批优化方案", "监控"],
    ["/ai-front-test", "/ai-front-test", "产品下批优化方案", "监控"],
    ["/ai-front-test/environment", "/ai-front-test/environment", "虚拟平台已就绪", "监控"],
    ["/settings", "/settings", "设置", "设置"],
    ["/configuration", "/configuration", "正文生成模型", "设置"],
    ["/ai-config", "/ai-config", "正文生成模型", "设置"],
    ["/real-integration", "/real-integration", "正文生成模型", "设置"],
    ["/operations", "/operations", "运行状态", "设置"]
];
export const demoPageCases: DemoPageCase[] = rows.map(([route, href, expected, group]) => ({ route, href, expected, group }));
export const demoExtraCases: DemoPageCase[] = [
    { route: "email-direct", href: "/hosted/email", expected: "公开结果与状态", group: "邮件" },
    { route: "sample-review", href: "/hosted/review/demo-sample", expected: "代表样文", group: "邮件" },
    { route: "preferences", href: "/hosted/preferences/demo-preferences", expected: "保存通知偏好", group: "邮件" },
    { route: "product-strategy", href: "/products/orbitdesk?tab=strategy", expected: "场景解读", group: "调研" },
    { route: "product-research", href: "/products/orbitdesk?tab=geo", expected: "任务完成", group: "调研" },
    { route: "free-result", href: "/free-production?batch=demo-free-ready", expected: "核对正文与来源", group: "正文" },
    ...["content", "ai", "website", "alerts", "history"].map(tab => ({ route: `monitor-${tab}`, href: `/content-monitor?tab=${tab}`, expected: { content: "内容表现明细", ai: "产品下批优化方案", website: "官网监控", alerts: "失败告警", history: "系统自动化记录" }[tab]!, group: "监控" })),
    ...["models", "connections", "rules", "logs"].map(tab => ({ route: `settings-${tab}`, href: `/settings?tab=${tab}`, expected: { models: "正文生成模型", connections: "发布连接", rules: "场景解读", logs: "设置" }[tab]!, group: "设置" })),
    { route: "published-article", href: "/demo-article/demo-task-1", expected: "从资料到可检查的结果", group: "正文" },
    { route: "deployment", href: "/?role=deployment", expected: "部署", group: "设置" }
];
