-- V5 WeChat-only manual template selection and approved presentation artifacts.
CREATE TABLE IF NOT EXISTS wechat_template_selection (
  id VARCHAR(64) PRIMARY KEY,
  draft_version_id VARCHAR(64) NOT NULL,
  source_content_hash CHAR(64) NOT NULL,
  platform_key VARCHAR(32) NOT NULL,
  recommender_version VARCHAR(64) NOT NULL,
  recommended_template_id VARCHAR(64) NULL,
  recommendation_result JSON NOT NULL,
  selected_template_id VARCHAR(64) NOT NULL,
  template_version VARCHAR(64) NOT NULL,
  selection_source VARCHAR(32) NOT NULL,
  selection_reason TEXT NULL,
  status VARCHAR(32) NOT NULL,
  idempotency_key VARCHAR(191) NOT NULL,
  request_hash CHAR(64) NOT NULL,
  selected_by VARCHAR(128) NOT NULL,
  selected_at DATETIME NOT NULL,
  UNIQUE KEY uq_wechat_template_selection_idempotency (draft_version_id, idempotency_key),
  INDEX idx_wechat_template_selection_current (draft_version_id, status, selected_at)
);

CREATE TABLE IF NOT EXISTS wechat_presentation_artifact (
  id VARCHAR(64) PRIMARY KEY,
  selection_id VARCHAR(64) NOT NULL,
  draft_version_id VARCHAR(64) NOT NULL,
  source_content_hash CHAR(64) NOT NULL,
  input_hash CHAR(64) NOT NULL,
  template_id VARCHAR(64) NOT NULL,
  template_version VARCHAR(64) NOT NULL,
  html MEDIUMTEXT NULL,
  html_hash CHAR(64) NULL,
  validation_result JSON NOT NULL,
  review_status VARCHAR(32) NOT NULL DEFAULT 'pending_review',
  cover_image_ref TEXT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reviewed_by VARCHAR(128) NULL,
  reviewed_at DATETIME NULL,
  review_reason TEXT NULL,
  publish_status VARCHAR(32) NOT NULL DEFAULT 'not_sent',
  external_draft_id VARCHAR(255) NULL,
  draft_url TEXT NULL,
  publish_error TEXT NULL,
  published_at DATETIME NULL,
  UNIQUE KEY uq_wechat_presentation_input (selection_id, input_hash),
  INDEX idx_wechat_presentation_review (review_status, created_at),
  INDEX idx_wechat_presentation_publish (publish_status, created_at),
  INDEX idx_wechat_presentation_draft (draft_version_id, created_at)
);
