CREATE TABLE IF NOT EXISTS knowledge_collection_source (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  entry_url TEXT NULL,
  account_id VARCHAR(255) NULL,
  default_knowledge_base_id VARCHAR(64) NOT NULL,
  default_product_id VARCHAR(64) NULL,
  default_product_name VARCHAR(255) NULL,
  public_use_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  schedule_hour TINYINT UNSIGNED NOT NULL DEFAULT 8,
  last_status VARCHAR(32) NULL,
  last_error TEXT NULL,
  last_collected_at DATETIME NULL,
  next_collect_at DATETIME NOT NULL,
  row_version INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_collection_source_due (enabled, next_collect_at),
  INDEX idx_collection_source_account (source_type, account_id)
);

CREATE TABLE IF NOT EXISTS knowledge_collection_run (
  id VARCHAR(64) PRIMARY KEY,
  source_id VARCHAR(64) NULL,
  status VARCHAR(32) NOT NULL,
  discovered_count INT UNSIGNED NOT NULL DEFAULT 0,
  collected_count INT UNSIGNED NOT NULL DEFAULT 0,
  updated_count INT UNSIGNED NOT NULL DEFAULT 0,
  unchanged_count INT UNSIGNED NOT NULL DEFAULT 0,
  failed_count INT UNSIGNED NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  started_at DATETIME NOT NULL,
  completed_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_collection_run_source (source_id, started_at),
  INDEX idx_collection_run_status (status, started_at)
);

CREATE TABLE IF NOT EXISTS knowledge_collection_snapshot (
  id VARCHAR(64) PRIMARY KEY,
  run_id VARCHAR(64) NOT NULL,
  source_id VARCHAR(64) NOT NULL,
  source_name VARCHAR(120) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  title VARCHAR(500) NOT NULL,
  canonical_url TEXT NOT NULL,
  canonical_url_hash CHAR(64) NOT NULL,
  content_hash CHAR(64) NULL,
  content LONGTEXT NOT NULL,
  excerpt TEXT NOT NULL,
  entity_type VARCHAR(32) NOT NULL,
  entity_name VARCHAR(255) NOT NULL,
  product_id VARCHAR(64) NULL,
  knowledge_base_id VARCHAR(64) NOT NULL,
  knowledge_base_name VARCHAR(255) NOT NULL,
  classification_confidence DECIMAL(6,5) NOT NULL DEFAULT 0,
  classification_reasons JSON NOT NULL,
  classifier_version VARCHAR(64) NOT NULL,
  collection_status VARCHAR(32) NOT NULL,
  governance_status VARCHAR(32) NOT NULL,
  governance_message TEXT NULL,
  material_id VARCHAR(64) NULL,
  collected_at DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_collection_snapshot_today (collected_at, source_id),
  INDEX idx_collection_snapshot_url (canonical_url_hash, collected_at),
  INDEX idx_collection_snapshot_kb (knowledge_base_id, collected_at),
  INDEX idx_collection_snapshot_product (product_id, collected_at)
);
