-- V5 WeChat presentation artifacts. Selection and rendering are server-side and versioned.
CREATE TABLE IF NOT EXISTS wechat_presentation_artifact (
  id VARCHAR(64) PRIMARY KEY,
  draft_version_id VARCHAR(64) NOT NULL,
  source_content_hash CHAR(64) NOT NULL,
  input_hash CHAR(64) NOT NULL,
  selector_version VARCHAR(64) NOT NULL,
  selection_status VARCHAR(32) NOT NULL,
  template_id VARCHAR(64) NULL,
  template_family VARCHAR(32) NULL,
  selected_score INT NULL,
  runner_up_score INT NULL,
  business_reason TEXT NOT NULL,
  candidate_scores JSON NOT NULL,
  input_snapshot JSON NOT NULL,
  html MEDIUMTEXT NULL,
  html_hash CHAR(64) NULL,
  validation_result JSON NOT NULL,
  review_status VARCHAR(32) NOT NULL DEFAULT 'pending_review',
  cover_image_ref TEXT NULL,
  created_by VARCHAR(128) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  reviewed_by VARCHAR(128) NULL,
  reviewed_at DATETIME NULL,
  review_reason TEXT NULL,
  publish_status VARCHAR(32) NOT NULL DEFAULT 'not_sent',
  external_draft_id VARCHAR(255) NULL,
  draft_url TEXT NULL,
  publish_error TEXT NULL,
  published_at DATETIME NULL,
  UNIQUE KEY uq_wechat_presentation_source (draft_version_id, source_content_hash, selector_version, input_hash),
  INDEX idx_wechat_presentation_review (review_status, created_at),
  INDEX idx_wechat_presentation_publish (publish_status, created_at),
  INDEX idx_wechat_presentation_draft (draft_version_id, created_at)
);
