import assert from "node:assert/strict";
import test from "node:test";
import ts from "typescript";
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
function load(relativePath) { const filePath = path.join(process.cwd(), relativePath); const output = ts.transpileModule(fs.readFileSync(filePath, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true }, fileName: filePath }).outputText; const module = { exports: {} }; new Function("require", "module", "exports", output)(require, module, module.exports); return module.exports; }
function fixture() { const chunk = { chunkId: "chunk-1", indexSnapshotId: "idx-1", namespace: "production_public", productId: "noteflow", productName: "Noteflow", knowledgeBaseIds: ["kb"], sourceId: "source-1", sourceRevisionId: "rev-1", primaryClaimId: "claim-1", claimIds: ["claim-1"], sourceLocator: { headingPath: ["能力"] }, semanticType: "claim_chunk", chunkTitle: "文档问答", summary: "基于资料回答", content: "基于资料回答并保留引用。", originalQuote: "基于资料回答并保留引用。", documentType: "official_product_page", authorityLevel: "A2", lifecycleStatus: "current", visibility: "public", supportMode: "direct", claimScope: "public_product", capabilityStatus: "current", conditions: [], limitations: [], scenarioTags: [], capabilityTags: [], audienceTags: [], problemTags: [], channelTags: [], distilledTermIds: [], questionCandidateIds: [], conflictGroupIds: [], rulePackageVersionId: "rule-1", contentHash: "a", semanticHash: "a", duplicateClusterId: "a", status: "active", chunkerVersion: "v1" }; const candidate = { chunk, channels: ["required"], rawScores: { required: 1 }, rrfScore: .1, rerankScore: .5, selected: true, exclusionReasons: [], selectionReasons: ["required"], evidenceRoles: ["product_mechanism", "method_step", "human_boundary"] }; const run = { retrievalRunId: "run-1", retrievalRequestId: "req-1", indexSnapshotIds: ["idx-1"], routeId: "route-wechat-tool-guide", routeVersion: "v1", retrievalPolicyVersion: "v1", status: "completed", candidates: [candidate], selectedChunkIds: ["chunk-1"], missingEvidenceRoles: [], startedAt: new Date().toISOString(), completedAt: new Date().toISOString() }; const request = { retrievalRequestId: "req-1", matrixItemId: "matrix-1", productId: "noteflow", productName: "Noteflow", namespace: "production_public", language: "zh-CN", title: "指南", channel: "wechat", contentType: "guide", platformContentType: "implicit_tool_guide", targetAudience: "知识工作者", sourceProblem: "资料分散", distilledTermIds: [], rulePackageVersionId: "rule-1", permissionScope: ["public"], lifecycleStatuses: ["current"], requestedAt: new Date().toISOString() }; return { run, request }; }

test("Final EvidencePack decision follows required evidence slots and config", () => { const { buildFinalEvidencePack } = load("src/lib/v5/rag/evidence-services.ts"); const { ragRetrievalRoutes } = load("src/lib/v5/rag/retrieval-route-registry.ts"); const { run, request } = fixture(); const base = { monthlyPlanId: "m", matrixVersionId: "mv", matrixItemId: "mi", taskId: "task", taskVersion: 1, request, route: ragRetrievalRoutes.implicit_tool_guide, retrievalRun: run, rulePackageVersionId: "rule-1", sourceSnapshotHash: "hash", taskSnapshot: {}, governanceSnapshot: {} }; const pending = buildFinalEvidencePack({ ...base, infrastructure: { status: "pending_config", mysql: { status: "ready", missingConfig: [] }, opensearch: { status: "pending_config", missingConfig: ["OPENSEARCH_URL"] }, embedding: { status: "pending_config", missingConfig: ["RAG_EMBEDDING_PROVIDER"] } } }); assert.equal(pending.decision, "pending_config"); const ready = buildFinalEvidencePack({ ...base, embeddingProvider: "qwen_embedding", embeddingModel: "text-embedding-v3", infrastructure: { status: "ready", mysql: { status: "ready", missingConfig: [] }, opensearch: { status: "ready", missingConfig: [] }, embedding: { status: "ready", provider: "qwen_embedding", model: "text-embedding-v3", missingConfig: [] } } }); assert.equal(ready.decision, "generatable"); });
test("Final EvidencePack is rejected after task, rule or index changes", () => { const { buildFinalEvidencePack, assertFinalEvidencePackUsable } = load("src/lib/v5/rag/evidence-services.ts"); const { ragRetrievalRoutes } = load("src/lib/v5/rag/retrieval-route-registry.ts"); const { run, request } = fixture(); const pack = buildFinalEvidencePack({ monthlyPlanId: "m", matrixVersionId: "mv", matrixItemId: "mi", taskId: "task", taskVersion: 1, request, route: ragRetrievalRoutes.implicit_tool_guide, retrievalRun: run, rulePackageVersionId: "rule-1", sourceSnapshotHash: "hash", embeddingProvider: "qwen_embedding", embeddingModel: "model", taskSnapshot: {}, governanceSnapshot: {}, infrastructure: { status: "ready", mysql: { status: "ready", missingConfig: [] }, opensearch: { status: "ready", missingConfig: [] }, embedding: { status: "ready", missingConfig: [] } } }); assert.doesNotThrow(() => assertFinalEvidencePackUsable(pack, { taskId: "task", taskVersion: 1, rulePackageVersionId: "rule-1", activeIndexSnapshotIds: ["idx-1"] })); assert.throws(() => assertFinalEvidencePackUsable(pack, { taskId: "task", taskVersion: 2, rulePackageVersionId: "rule-1", activeIndexSnapshotIds: ["idx-1"] }), /task_snapshot_mismatch/); assert.throws(() => assertFinalEvidencePackUsable(pack, { taskId: "task", taskVersion: 1, rulePackageVersionId: "rule-1", activeIndexSnapshotIds: ["idx-2"] }), /index_snapshot_inactive/); });
test("Final EvidencePack requires an immutable timestamp and at least one index snapshot", () => { const { assertFinalEvidencePackUsable } = load("src/lib/v5/rag/evidence-services.ts"); const incomplete = { evidencePackId: "pack", decision: "generatable", taskId: "task", taskVersion: 1, rulePackageVersionId: "rule", indexSnapshotIds: [], snapshotHash: "hash", immutableAt: "" }; assert.throws(() => assertFinalEvidencePackUsable(incomplete, { taskId: "task", taskVersion: 1, rulePackageVersionId: "rule", activeIndexSnapshotIds: [] }), /index_snapshot_missing/); });
